name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Simulate long running
      run: |
        echo "CI Started"
        sleep 1m
        echo "Sleep is over"
